import { applyD1Migrations, env } from "cloudflare:test";
import type { D1Migration } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { runMaintenance } from "../src/maintenance/cleanup";
declare global { namespace Cloudflare { interface Env { DB:D1Database;ATTACHMENTS:R2Bucket;CURSOR_MAC_KEY:string;RATE_LIMIT_MAC_KEY:string;TEST_MIGRATIONS:D1Migration[]; } } }
const ACCOUNT="A0000000-0000-4000-8000-00000000000A";const DEVICE="B0000000-0000-4000-8000-000000000001";const ATTACHMENT="70000000-0000-4000-8000-000000000001";const OLD="2026-08-20T00:00:00Z";const NOW=Date.now()+3*86_400_000;
beforeAll(async()=>{await applyD1Migrations(env.DB,env.TEST_MIGRATIONS);});
beforeEach(async()=>{for(const table of ["pairing_claim","pairing_session","attachment","device","account"])await env.DB.prepare(`DELETE FROM ${table}`).run();const listed=await env.ATTACHMENTS.list();if(listed.objects.length)await env.ATTACHMENTS.delete(listed.objects.map(x=>x.key));await env.DB.prepare("INSERT INTO account(account_id,created_at)VALUES(?,?)").bind(ACCOUNT,OLD).run();await env.DB.prepare(`INSERT INTO device(account_id,device_id,space_id,platform,linked_at,key_generation)VALUES(?,?, 'MAC_SPACE','macos',?,1)`).bind(ACCOUNT,DEVICE,OLD).run();});
describe("scheduled maintenance",()=>{
 it("deletes only old unreferenced R2 objects and abandons missing allocations",async()=>{const key="obj/D0000000-0000-4000-8000-000000000001";const orphan="obj/D0000000-0000-4000-8000-000000000002";await env.ATTACHMENTS.put(key,new Uint8Array(35));await env.ATTACHMENTS.put(orphan,new Uint8Array(35));await env.DB.prepare(`INSERT INTO attachment(account_id,attachment_id,origin_space_id,r2_object_key,kind,state,source_byte_size,ciphertext_byte_size,ciphertext_hash,key_generation,file_name_enc,mime_type_enc,wrapped_file_key_enc,created_at)VALUES(?,?, 'MAC_SPACE',?,'attachment','allocated',1,35,?,1,?,?,?,?)`).bind(ACCOUNT,ATTACHMENT,key,"a".repeat(64),"QQ==","QQ==","QQ==",OLD).run();const report=await runMaintenance(env,NOW+3*86_400_000);expect(report.orphan_objects_deleted).toBe(1);expect(await env.ATTACHMENTS.head(key)).not.toBeNull();expect(await env.ATTACHMENTS.head(orphan)).toBeNull();expect((await env.DB.prepare("SELECT state FROM attachment").first<{state:string}>())?.state).toBe("allocated");});
 it("marks an old allocated row abandoned when its object is absent",async()=>{const key="obj/D0000000-0000-4000-8000-000000000003";await env.DB.prepare(`INSERT INTO attachment(account_id,attachment_id,origin_space_id,r2_object_key,kind,state,source_byte_size,ciphertext_byte_size,ciphertext_hash,key_generation,file_name_enc,mime_type_enc,wrapped_file_key_enc,created_at)VALUES(?,?, 'MAC_SPACE',?,'attachment','allocated',1,35,?,1,?,?,?,?)`).bind(ACCOUNT,ATTACHMENT,key,"a".repeat(64),"QQ==","QQ==","QQ==",OLD).run();const report=await runMaintenance(env,NOW);expect(report.attachments_abandoned).toBe(1);expect((await env.DB.prepare("SELECT state FROM attachment").first<{state:string}>())?.state).toBe("abandoned");});
 it("removes pairing rows only after expiry plus grace",async()=>{const session="30000000-0000-4000-8000-000000000001";await env.DB.prepare(`INSERT INTO pairing_session(session_id,account_id,session_lookup_hash,created_by_device_id,created_at,expires_at)VALUES(?,?,?,?,?,?)`).bind(session,ACCOUNT,"a".repeat(64),DEVICE,"2026-08-20T00:00:00Z","2026-08-20T00:05:00Z").run();const report=await runMaintenance(env,NOW);expect(report.pairing_sessions_deleted).toBe(1);});
});
