import type { AuthContext } from "../auth/deviceToken";
import { ApiError } from "../contracts/error";
import { claimRedeemVerifier } from "../contracts/pairing";
import { constantTimeHexEqual } from "../contracts/recovery";

function invalid():ApiError{return new ApiError("PAIRING_INVALID");}
function conflict():ApiError{return new ApiError("PAIRING_STATE_CONFLICT");}
interface SessionRow{session_id:string;account_id:string;session_lookup_hash:string;expires_at:string;closed_at:string|null;}
interface ClaimRow{session_id:string;account_id:string;claim_id:string;claim_lookup_b64:string;claim_envelope:string;claim_redeem_verifier:string;state:string;delivery_envelope:string|null;new_device_id:string|null;new_device_space_id:string|null;new_device_platform:string|null;new_device_display_name_enc:string|null;device_token_hash:string|null;linked_at:string|null;}
async function session(db:D1Database,id:string):Promise<SessionRow|null>{return db.prepare("SELECT session_id,account_id,session_lookup_hash,expires_at,closed_at FROM pairing_session WHERE session_id=?").bind(id).first<SessionRow>();}
function open(row:SessionRow|null):row is SessionRow{return row!==null&&row.closed_at===null&&Date.parse(row.expires_at)>Date.now();}

export async function createPairingSession(db:D1Database,auth:AuthContext,input:{sessionId:string;lookupHash:string}){const existing=await session(db,input.sessionId);if(existing){if(existing.account_id===auth.account_id&&existing.session_lookup_hash===input.lookupHash&&open(existing))return{status:"replayed" as const,session_id:input.sessionId,expires_at:existing.expires_at};throw conflict();}const now=new Date();const expires=new Date(now.getTime()+300_000).toISOString();try{await db.prepare(`INSERT INTO pairing_session(session_id,account_id,session_lookup_hash,created_by_device_id,created_at,expires_at,closed_at)VALUES(?,?,?,?,?,?,NULL)`).bind(input.sessionId,auth.account_id,input.lookupHash,auth.device_id,now.toISOString(),expires).run();}catch{throw conflict();}return{status:"created" as const,session_id:input.sessionId,expires_at:expires};}
export async function submitPairingClaim(db:D1Database,sessionId:string,input:{sessionLookupHash:string;claimId:string;claimLookup:string;claimEnvelope:string;claimRedeemVerifier:string}){const s=await session(db,sessionId);if(!open(s)||s.session_lookup_hash!==input.sessionLookupHash)throw invalid();try{await db.prepare(`INSERT INTO pairing_claim(session_id,account_id,claim_id,claim_lookup_b64,claim_envelope,claim_redeem_verifier,state,submitted_at)VALUES(?,?,?,?,?,?,'submitted',?)`).bind(sessionId,s.account_id,input.claimId,input.claimLookup,input.claimEnvelope,input.claimRedeemVerifier,new Date().toISOString()).run();}catch{throw conflict();}return{status:"submitted" as const,claim_id:input.claimId};}
export async function listPairingClaims(db:D1Database,auth:AuthContext,sessionId:string){const s=await session(db,sessionId);if(!open(s)||s.account_id!==auth.account_id)throw invalid();const result=await db.prepare(`SELECT claim_id,claim_lookup_b64,claim_envelope,state FROM pairing_claim WHERE session_id=? AND state<>'consumed' ORDER BY submitted_at,claim_id`).bind(sessionId).all<{claim_id:string;claim_lookup_b64:string;claim_envelope:string;state:string}>();return{claims:result.results.map(x=>({claim_id:x.claim_id,claim_lookup:x.claim_lookup_b64,claim_envelope:x.claim_envelope,state:x.state}))};}
export async function approvePairingClaim(db:D1Database,auth:AuthContext,sessionId:string,claimId:string,input:{claimLookup:string;deliveryEnvelope:string;device:{deviceId:string;spaceId:string;platform:string;displayName:string|null;tokenHash:string}}){const s=await session(db,sessionId);if(!open(s)||s.account_id!==auth.account_id)throw invalid();const now=new Date().toISOString();const result=await db.prepare(`UPDATE pairing_claim SET state='approved',approved_at=?,approved_by_device_id=?,delivery_envelope=?,new_device_id=?,new_device_space_id=?,new_device_platform=?,new_device_display_name_enc=?,device_token_hash=?,linked_at=? WHERE session_id=? AND claim_id=? AND account_id=? AND claim_lookup_b64=? AND state='submitted'`).bind(now,auth.device_id,input.deliveryEnvelope,input.device.deviceId,input.device.spaceId,input.device.platform,input.device.displayName,input.device.tokenHash,now,sessionId,claimId,auth.account_id,input.claimLookup).run();if((result.meta.changes??0)!==1)throw conflict();return{status:"approved" as const,claim_id:claimId};}
async function claim(db:D1Database,sessionId:string,claimId:string):Promise<ClaimRow|null>{return db.prepare(`SELECT session_id,account_id,claim_id,claim_lookup_b64,claim_envelope,claim_redeem_verifier,state,delivery_envelope,new_device_id,new_device_space_id,new_device_platform,new_device_display_name_enc,device_token_hash,linked_at FROM pairing_claim WHERE session_id=? AND claim_id=?`).bind(sessionId,claimId).first<ClaimRow>();}
export async function redeemPairingClaim(db:D1Database,sessionId:string,claimId:string,input:{claimLookup:{encoded:string;bytes:Uint8Array};claimRedeemAuth:Uint8Array}){const s=await session(db,sessionId);const c=await claim(db,sessionId,claimId);if(s===null||Date.parse(s.expires_at)<=Date.now()||c===null||c.claim_lookup_b64!==input.claimLookup.encoded)throw invalid();const candidate=await claimRedeemVerifier(sessionId,claimId,input.claimLookup.bytes,input.claimRedeemAuth);if(!constantTimeHexEqual(candidate,c.claim_redeem_verifier))throw invalid();if(c.state!=="approved"||s.closed_at!==null||c.delivery_envelope===null||c.new_device_id===null||c.new_device_space_id===null||c.new_device_platform===null||c.device_token_hash===null||c.linked_at===null)throw conflict();try{await db.batch([db.prepare(`INSERT INTO device(account_id,device_id,space_id,platform,display_name_enc,linked_at,revoked_at,key_generation,token_hash)VALUES(?,?,?,?,?,?,NULL,1,?)`).bind(c.account_id,c.new_device_id,c.new_device_space_id,c.new_device_platform,c.new_device_display_name_enc,c.linked_at,c.device_token_hash),db.prepare(`UPDATE pairing_claim SET state='consumed',consumed_at=? WHERE session_id=? AND claim_id=? AND state='approved'`).bind(new Date().toISOString(),sessionId,claimId),db.prepare(`UPDATE pairing_session SET closed_at=? WHERE session_id=? AND closed_at IS NULL`).bind(new Date().toISOString(),sessionId)]);}catch{throw conflict();}return{status:"consumed" as const,device_id:c.new_device_id,delivery_envelope:c.delivery_envelope};}
